spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=jwt_security;encrypt=true;trustServerCertificate=true;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mssql
      database-platform: org.hibernate.dialect.SQLServer2012Dialect
